steps:
  - name: "gcr.io/cloud-builders/npm"
    id: Test
    args:
      - "install"
      - "test"
  - name: "gcr.io/cloud-builders/docker"
    id: Build
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/${IMAGE}", "."]
  - name: "gcr.io/cloud-builders/docker"
    id: Push
    args: ["push", "gcr.io/${PROJECT_ID}/${IMAGE}"]
images: ["gcr.io/${PROJECT_ID}/${IMAGE}"]
